services:
  todo:
    build: /opt/Microservices/allservice/todo6
    ports:
      - '80:80'
    container_name: todo_apache
    volumes:
      - v1:/var/www/html/
    network_mode: 
      bridge

  traffic:
    build: /opt/Microservices/allservice/traffic-light
    ports:
      - '81:80'
    container_name: traffic_apache
    volumes:
      - v2:/var/www/html/
    network_mode: 
      bridge

  season:
    build: /opt/Microservices/allservice/season-switcher
      - '82:80'
    container_name: season_apache
    volumes:
      - v3:/var/www/html/
    network_mode: 
      bridge

volumes:
  v1:
  v2:
  v3: