services:
  traffic:
    build: ./traffic-light/
    ports:
      - '81:80'
    container_name: traffic_apache
    volumes:
      - myapp2: /var/www/html/
    network_mode: 
        bridge

  season:
    build: ./season-switcher/
    ports:
      - '82:80'
    container_name: season_apache
    volumes:
      - myapp3: /var/www/html/
    network_mode: 
       bridge

volumes:
  myapp1:
  myapp2:
  myapp3: