services:
  todo:
    build: ./todo6/
    ports:
      - '80:80'
    container_name: todo_apache
    volumes:
      - myapp1: /var/www/html/
    network_mode: 
      bridge

  traffic:
    build: ./traffic-light/
    ports:
      - '80:80'
    container_name: traffic_apache
    volumes:
      - myapp2: /var/www/html/
    network_mode: 
      bridge

  season:
    build: ./season-switcher/
    ports:
      - '80:80'
    container_name: season_apache
    volumes:
      - myapp3: /var/www/html/
    network_mode: 
      bridge

volumes:
  myapp1:
  myapp2:
  myapp3: